package com.duongam.demo.util;


public interface ErrorCode {
    String EM01 = "User type is required. ";
    String EM02 = "Name is required. ";
    String EM03 = "Email address is required. ";
    String EM04 = "Email address is existed. Please check and input another email address.";
    String EM05 = "Email address is invalid. Please check and input again.";
    String EM06 = "Phone is required. ";
    String EM07 = "Phone is invalid. Please check and input again";
    String EM08 = "Date of birth is required. ";
    String EM09 = "User is created successfully.";
    String EM10 = "User is updated successfully.";
    String EM11 = "Role is updated successfully.";
    String EM12 = "Syllabus name is required. ";
    String EM13 = "Level is required. ";
    String EM14 = "Attendee number is required. ";
    String EM15 = "Technical requirement(s) is required. ";
    String EM16 = "Course objectives are required. ";
    String EM17 = "Unit name is required. ";
    String EM18 = "Content name is required. ";
    String EM19 = "Output standard is required. ";
    String EM20 = "Training time is required. ";
    String EM21 = "Delivery type is required. ";
    String EM22 = "Delete all content of the Day?";
    String EM23 = "Please input at least one day.";
    String EM24 = "Please input at least one unit into this day.";
    String EM25 = "Please input at least one content into this unit.";
    String EM26 = "The duration exceeds 8 hours per day. Please check again.";
    String EM27 = "Quiz is required. ";
    String EM28 = "Assignment is required. ";
    String EM29 = "Final is required. ";
    String EM30 = "Final Theory is required. ";
    String EM31 = "Final Practice is required. ";
    String EM32 = "GPA is required. ";
    String EM33 = "Total of all assessment is not 100%. Please check again.";
    String EM34 = "File is required. ";
    String EM35 = "Program name is required. ";
    String EM36 = "General information is required. ";
    String EM37 = "Syllabus is required. ";
    String EM38 = "List of syllabuses is required. ";
    String EM39 = "File is required. ";
    String EM40 = "File is invalid. Please check and upload again. ";
    String EM41 = "Class name is required. ";
    String EM42 = "Class time is required. ";
    String EM43 = "Location is required. ";
    String EM44 = "Trainer is required.";
    String EM45 = "Admin is required. ";
    String EM46 = "FSU is required.";
    String EM47 = "Time frame is required. ";
    String EM48 = "Training program is required";
    String EM49 = "If you change training program, list of syllabuses will be replaced by new training program";
    String EM50 = "Do you want to delete <class name> class? ";
    String EM51 = "Do you want to update schedule? This session of class only. All Session of this class.";
    String EM52 = "Token not found";
    String EM53 = "Phone number must be 10 digits";
    String EM54 = "Gender is required.";
    String EM55 = "Password must contain at least one letter, one digit, and be 8-12 characters long";
    String EM56 = "Token expires";
    String EM57 = "Token was confirmed";
    String EM58 = "Your link restore password has been sent to your email";
    String EM59 = "Your email or password does not exist";
    String EM60 = "Your password has been reset.";
    String EM61 = "Completed registration";
    String EM62 = "Page has no content because search value";
    String EM63 = "User not active";

}

